In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error, mean_absolute_error

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, classification_report
import warnings
warnings.filterwarnings('ignore')

In [3]:
data=r"C:\Users\Asus\OneDrive\Desktop\Machine learning\Medical_report.csv"
df=pd.read_csv(data)

In [4]:
df.head()

,Duration,Average_Pulse,Max_Pulse,Calorie_Burnage,Hours_Work,Hours_Sleep
0,30,80.0,120,240,10,7
1,30,85.0,120,250,10,7
2,45,90.0,130,260,8,7
3,45,95.0,130,270,8,7
4,45,100.0,140,280,0,7

In [5]:
df.tail()

,Duration,Average_Pulse,Max_Pulse,Calorie_Burnage,Hours_Work,Hours_Sleep
10,80,134.0,140,400,8,6
11,35,NaN,140,200,8,7
12,100,145.0,150,300,5,6
13,45,100.0,120,250,8,9
14,65,100.0,130,300,9,8

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Duration         15 non-null     int64
 1   Average_Pulse    14 non-null     float64
 2   Max_Pulse        15 non-null     int64
 3   Calorie_Burnage  15 non-null     int64
 4   Hours_Work       15 non-null     int64
 5   Hours_Sleep      15 non-null     int64
dtypes: float64(1), int64(5)
memory usage: 852.0 bytes

In [7]:
df.shape

(15, 6)

In [8]:
df.isnull().sum()

Duration           0
Average_Pulse      1
Max_Pulse          0
Calorie_Burnage    0
Hours_Work         0
Hours_Sleep        0
dtype: int64

In [9]:
df['Average_Pulse'].fillna(df['Average_Pulse'].mean(), inplace=True)

In [10]:
df.isnull().sum()

Duration           0
Average_Pulse      0
Max_Pulse          0
Calorie_Burnage    0
Hours_Work         0
Hours_Sleep        0
dtype: int64

In [11]:
scaler=StandardScaler()
standardized_data= scaler.fit_transform(df)
standardized_df=pd.DataFrame(standardized_data, columns=df.columns)

In [12]:
df.head()

,Duration,Average_Pulse,Max_Pulse,Calorie_Burnage,Hours_Work,Hours_Sleep
0,30,80.0,120,240,10,7
1,30,85.0,120,250,10,7
2,45,90.0,130,260,8,7
3,45,95.0,130,270,8,7
4,45,100.0,140,280,0,7

In [13]:
x= df[['Calorie_Burnage','Duration','Hours_Work','Hours_Sleep']]
y = df['Average_Pulse']

In [14]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.25,random_state=42)

In [15]:
xtrain

    Calorie_Burnage  Duration  Hours_Work  Hours_Sleep
5               290        60           7            8
8               320        75           0            8
2               260        45           8            7
1               250        30          10            7
14              300        65           9            8
4               280        45           0            7
7               310        60           8            8
10              400        80           8            6
12              300       100           5            6
3               270        45           8            7
6               300        60           7            8

In [28]:
xtest

    Calorie_Burnage  Duration  Hours_Work  Hours_Sleep
9               330        75           8            8
11              200        35           8            7
0               240        30          10            7
13              250        45           8            9

In [29]:
pdict=LinearRegression()

In [30]:
pdict.fit(xtrain,ytrain)

LinearRegression()

In [31]:
y_predict=pdict.predict(xtest)

In [32]:
y_predict=pdict.predict([[450,100,15,5]])

In [33]:
pdict.score(x,y)

0.7735309630863431

In [34]:
x.shape

(15, 4)

In [35]:
y_predict.shape

(1,)

In [36]:
data = pd.DataFrame(y_predict, columns=['Average_Pulse',])
print(data)

   Average_Pulse
0     154.080424

In [38]:
r2_score(y,pdict.predict(xtest))

ValueError: Found input variables with inconsistent numbers of samples: [15, 4]